name: Deploy

on:
 push:
   branches:
     - main

jobs:
 build:
   runs-on: ubuntu-20.04

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup Node
       uses: actions/setup-node@v2
       with:
         node-version: 14.x
         cache: npm

     - name: Install dependencies
       run: npm install --frozen-lockfile

     - name: Build
       run: npm run build

     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: out
